# Generated by Django 3.1.5 on 2021-08-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='NULL', max_length=255)),
                ('lname', models.CharField(default='NULL', max_length=255)),
                ('mname', models.CharField(default='NULL', max_length=255)),
                ('dateofbirth', models.DateField(max_length=10)),
                ('email', models.EmailField(max_length=255)),
                ('gender', models.CharField(default='NULL', max_length=50)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('file', models.FileField(default=0, upload_to='documents/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
